source:      .
destination: ./_site
plugins_dir:     ./_plugins
layouts_dir:     ./_layouts
include:     ['.htaccess']
exclude:     
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
  - vendor
keep_files:  ['.git','.svn']
timezone:    nil

future:      true
show_drafts: nil
limit_posts: 0
highlighter:    pygments

author: Daniel Marchant

safe: true
lsi: false

permalink: /blog/:year/:month/:day/:title

# relative_permalinks: true

paginate_path: 'page:num'

markdown:      kramdown
markdown_ext:  markdown,mkd,mkdn,md
textile_ext:   textile

# defaults
sass:
  syntax: sass        # scss|sass
  style:  expanded  # nested|expanded|compact|compressed